nonisolated let StringCatalog: [String: [Language: String]] = [
    // MARK: - Login / Register
    "login.title": [.zhHans: "登录", .en: "Login"],
    "login.register_title": [.zhHans: "注册", .en: "Register"],
    "login.account_placeholder": [.zhHans: "账户", .en: "Account"],
    "login.password_placeholder": [.zhHans: "密码", .en: "Password"],
    "login.name_placeholder": [.zhHans: "昵称", .en: "Nickname"],
    "login.login_button": [.zhHans: "登录", .en: "Login"],
    "login.register_button": [.zhHans: "注册", .en: "Register"],
    "login.switch_to_register": [.zhHans: "没有账户？注册", .en: "No account? Register"],
    "login.switch_to_login": [.zhHans: "已有账户？登录", .en: "Have an account? Login"],
    "login.account_password_required": [.zhHans: "请输入账户和密码", .en: "Please enter account and password"],
    "login.all_required": [.zhHans: "请填写账户、昵称和密码", .en: "Please enter account, nickname and password"],
    "login.register_success": [.zhHans: "注册成功，请登录", .en: "Registration successful, please login"],
    "login.logout": [.zhHans: "退出登录", .en: "Logout"],
    "login.logout_confirm": [.zhHans: "确定要退出登录吗？", .en: "Are you sure you want to logout?"],

    // MARK: - Conversation List
    "conv.title": [.zhHans: "会话", .en: "Conversations"],
    "conv.new_chat": [.zhHans: "新建聊天", .en: "New Chat"],
    "conv.new_group": [.zhHans: "创建群组", .en: "New Group"],
    "conv.search_placeholder": [.zhHans: "搜索", .en: "Search"],
    "conv.no_conversations": [.zhHans: "暂无会话", .en: "No conversations"],
    "conv.disconnected": [.zhHans: "连接已断开", .en: "Disconnected"],
    "conv.mention": [.zhHans: "有人@我", .en: "Someone @ me"],
    "conv.delete_confirm": [.zhHans: "确定删除会话？", .en: "Delete this conversation?"],
    "conv.unread": [.zhHans: "未读", .en: "unread"],

    // MARK: - Chat
    "chat.placeholder": [.zhHans: "输入消息...", .en: "Type a message..."],
    "chat.send": [.zhHans: "发送", .en: "Send"],
    "chat.detail": [.zhHans: "聊天详情", .en: "Chat Details"],
    "chat.p2p_detail": [.zhHans: "聊天信息", .en: "Chat Info"],
    "chat.no_messages": [.zhHans: "暂无消息", .en: "No messages yet"],
    "chat.typing": [.zhHans: "正在输入...", .en: "Typing..."],

    // MARK: - Contacts
    "contact.title": [.zhHans: "通讯录", .en: "Contacts"],
    "contact.add": [.zhHans: "添加联系人", .en: "Add Contact"],
    "contact.add_button": [.zhHans: "添加", .en: "Add"],
    "contact.delete_title": [.zhHans: "删除联系人", .en: "Delete Contact"],
    "contact.delete_confirm_message": [.zhHans: "确定要删除「%@」吗？", .en: "Are you sure you want to delete \"%@\"?"],
    "contact.delete_button": [.zhHans: "删除", .en: "Delete"],
    "contact.delete_confirm_default": [.zhHans: "确定要删除该联系人吗？", .en: "Are you sure you want to delete this contact?"],
    "contact.user_id_placeholder": [.zhHans: "用户ID", .en: "User ID"],
    "contact.nickname_placeholder": [.zhHans: "备注名", .en: "Nickname"],
    "contact.remove_confirm": [.zhHans: "确定删除联系人？", .en: "Remove this contact?"],
    "contact.no_contacts": [.zhHans: "暂无联系人", .en: "No contacts"],

    // MARK: - Profile
    "profile.title": [.zhHans: "我的", .en: "Profile"],
    "profile.account_label": [.zhHans: "账号:", .en: "Account:"],
    "profile.id_label": [.zhHans: "ID:", .en: "ID:"],
    "profile.user_info": [.zhHans: "个人信息", .en: "User Info"],
    "profile.settings": [.zhHans: "设置", .en: "Settings"],

    // MARK: - Settings
    "settings.title": [.zhHans: "设置", .en: "Settings"],
    "settings.theme": [.zhHans: "主题", .en: "Theme"],
    "settings.language": [.zhHans: "语言", .en: "Language"],
    "settings.theme_system": [.zhHans: "跟随系统", .en: "System"],
    "settings.theme_light": [.zhHans: "浅色", .en: "Light"],
    "settings.theme_dark": [.zhHans: "深色", .en: "Dark"],

    // MARK: - Group
    "group.create": [.zhHans: "创建群组", .en: "Create Group"],
    "group.create_button": [.zhHans: "创建", .en: "Create"],
    "group.name_placeholder": [.zhHans: "群组名称", .en: "Group Name"],
    "group.member_count": [.zhHans: "%lld 位成员", .en: "%lld members"],
    "group.info": [.zhHans: "群信息", .en: "Group Info"],
    "group.members_title": [.zhHans: "群成员", .en: "Members"],
    "group.owner": [.zhHans: "群主", .en: "Owner"],
    "group.admin": [.zhHans: "管理员", .en: "Admin"],
    "group.member": [.zhHans: "成员", .en: "Member"],
    "group.leave_confirm_message": [.zhHans: "确定要退出群聊「%@」吗？", .en: "Are you sure you want to leave \"%@\"?"],
    "group.remove_confirm_title": [.zhHans: "移除成员", .en: "Remove Member"],
    "group.remove_confirm_message": [.zhHans: "确定要移除「%@」吗？", .en: "Are you sure you want to remove \"%@\"?"],
    "group.remove_button": [.zhHans: "移除", .en: "Remove"],
    "group.error_title": [.zhHans: "操作失败", .en: "Operation Failed"],
    "group.add_member_search": [.zhHans: "搜索用户...", .en: "Search users..."],
    "group.no_results": [.zhHans: "未找到用户", .en: "No users found"],
    "group.members": [.zhHans: "群成员", .en: "Members"],
    "group.add_member": [.zhHans: "添加成员", .en: "Add Member"],
    "group.remove_member": [.zhHans: "移出群组", .en: "Remove from Group"],
    "group.leave": [.zhHans: "退出群组", .en: "Leave Group"],
    "group.leave_confirm": [.zhHans: "确定退出群组？", .en: "Are you sure you want to leave?"],
    "group.dissolve": [.zhHans: "解散群组", .en: "Dissolve Group"],

    // MARK: - Search
    "search.title": [.zhHans: "搜索", .en: "Search"],
    "search.placeholder": [.zhHans: "搜索用户...", .en: "Search users..."],
    "search.no_results": [.zhHans: "未找到用户", .en: "No users found"],

    // MARK: - Errors
    "error.unauthorized": [.zhHans: "登录已过期，请重新登录", .en: "Session expired, please login again"],
    "error.decoding_failed": [.zhHans: "数据解析失败", .en: "Data decoding failed"],
    "error.timeout": [.zhHans: "请求超时", .en: "Request timeout"],
    "error.network": [.zhHans: "网络错误", .en: "Network error"],
    "error.unknown": [.zhHans: "未知错误", .en: "Unknown error"],
    "error.load_failed": [.zhHans: "加载失败", .en: "Load failed"],

    // MARK: - Common
    "common.confirm": [.zhHans: "确定", .en: "Confirm"],
    "common.cancel": [.zhHans: "取消", .en: "Cancel"],
    "common.save": [.zhHans: "保存", .en: "Save"],
    "common.delete": [.zhHans: "删除", .en: "Delete"],
    "common.done": [.zhHans: "完成", .en: "Done"],
    "common.back": [.zhHans: "返回", .en: "Back"],
    "common.close": [.zhHans: "关闭", .en: "Close"],
    "common.loading": [.zhHans: "加载中...", .en: "Loading..."],
    "common.empty": [.zhHans: "暂无内容", .en: "No content"],
    "common.online": [.zhHans: "在线", .en: "Online"],
    "common.offline": [.zhHans: "离线", .en: "Offline"],
]
