.PHONY: server server-stop macos macos-stop ios-deploy xcodegen build-info deploy deploy-status deploy-logs swagger init-githooks

GIT_HASH := $(shell git rev-parse --short HEAD 2>/dev/null || echo "unknown")
BUILD_INFO := client/Packages/IMCore/Sources/IMCore/BuildInfo.swift
# Deployment
-include .env
# Generate build info file (for client builds)
build-info:
	@echo '// Auto-generated by Makefile. Do not edit.' > $(BUILD_INFO)
	@echo 'import Foundation' >> $(BUILD_INFO)
	@echo '' >> $(BUILD_INFO)
	@echo 'enum BuildInfo {' >> $(BUILD_INFO)
	@echo '    static let gitCommit = "$(GIT_HASH)"' >> $(BUILD_INFO)
	@echo '}' >> $(BUILD_INFO)

# Generate Swagger/OpenAPI docs
swagger:
	cd server && swag init -g cmd/ziziphus/main.go -o docs/

# Initialize git hooks for this project
init-githooks:
	git config core.hooksPath .githooks
	@echo "✅ Git hooks configured (using .githooks/)"

# Backend server
server: server-stop swagger
	cd server/web && npm run build
	mkdir -p bin
	cd server && go build -ldflags "-X ziziphus/pkg/version.GitCommit=$(GIT_HASH)" -o ../bin/ziziphus ./cmd/ziziphus/
	cd server && nohup ../bin/ziziphus -c config/config.yaml > /dev/null 2>&1 &
	@echo "Server started"

server-stop:
	@pkill -f "bin/ziziphus" 2>/dev/null || true
	@echo "Server stopped"

APP_BUNDLE = client/.build/debug/IMApp-macOS.app

# macOS client
macos: build-info macos-stop
	cd client && swift build --product IMApp-macOS
	mkdir -p "$(APP_BUNDLE)/Contents/MacOS"
	cp client/.build/debug/IMApp-macOS "$(APP_BUNDLE)/Contents/MacOS/"
	if [ ! -f "$(APP_BUNDLE)/Contents/Info.plist" ]; then \
		echo '<?xml version="1.0" encoding="UTF-8"?>' > "$(APP_BUNDLE)/Contents/Info.plist"; \
		echo '<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">' >> "$(APP_BUNDLE)/Contents/Info.plist"; \
		echo '<plist version="1.0"><dict></dict></plist>' >> "$(APP_BUNDLE)/Contents/Info.plist"; \
	fi
	plutil -replace CFBundleShortVersionString -string "1.0" "$(APP_BUNDLE)/Contents/Info.plist" && \
	plutil -replace CFBundleExecutable -string IMApp-macOS "$(APP_BUNDLE)/Contents/Info.plist" && \
	plutil -replace CFBundleIdentifier -string space.siciv.pandaai.macos "$(APP_BUNDLE)/Contents/Info.plist" && \
	plutil -replace CFBundleName -string "Panda" "$(APP_BUNDLE)/Contents/Info.plist" && \
	plutil -replace CFBundleDisplayName -string "Panda" "$(APP_BUNDLE)/Contents/Info.plist" && \
	plutil -replace CFBundleVersion -string 1 "$(APP_BUNDLE)/Contents/Info.plist" && \
	plutil -replace CFBundlePackageType -string APPL "$(APP_BUNDLE)/Contents/Info.plist" && \
	plutil -replace LSMinimumSystemVersion -string "15.0" "$(APP_BUNDLE)/Contents/Info.plist" && \
	plutil -insert NSAppTransportSecurity -xml '<dict><key>NSAllowsArbitraryLoads</key><true/></dict>' "$(APP_BUNDLE)/Contents/Info.plist" 2>/dev/null; true
	open "$(APP_BUNDLE)"

macos-stop:
	pkill -f "IMApp-macOS" 2>/dev/null || true
	@echo "App closed"

# iOS client — build and deploy to physical device
ios-deploy: build-info xcodegen
	cd client && xcodebuild build \
		-project IMApp.xcodeproj \
		-scheme IMApp-iOS \
		-destination 'platform=iOS,name=$(IOS_DEVICE)' \
		-allowProvisioningUpdates \
		CODE_SIGN_STYLE=Automatic
	@echo "Build succeeded for $(IOS_DEVICE)"
	DERIVED=$$(xcodebuild -project client/IMApp.xcodeproj -showBuildSettings -scheme IMApp-iOS 2>/dev/null | grep BUILD_DIR | head -1 | awk '{print $$NF}'); \
	APP="$${DERIVED}/Debug-iphoneos/IMApp-iOS.app"; \
	if [ -d "$$APP" ]; then \
		if command -v ios-deploy >/dev/null 2>&1; then \
			ios-deploy -b "$$APP"; \
		elif xcrun devicectl list devices 2>/dev/null | grep -q "$(IOS_DEVICE)"; then \
			xcrun devicectl install app --device "$(IOS_DEVICE)" "$$APP"; \
		else \
			echo "App built at: $$APP"; \
			echo "Install manually via Xcode Devices window (Cmd+Shift+2)"; \
		fi \
	else \
		echo "App not found at expected path, checking DerivedData..."; \
	fi

xcodegen:
	cd client && xcodegen generate

# Code quality
.PHONY: lint lint-web lint-server

lint-web:
	cd server/web && npx oxlint ./src

lint-server:
	cd server && golangci-lint run ./... --new

lint: lint-web lint-server

# =============================================================================
# Remote deploy
# =============================================================================

deploy:
	@echo "=== 1/3 Build frontend ==="
	cd server/web && npm run build
	@echo "=== 2/3 Cross-compile Linux binary ==="
	cd server && GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -ldflags "-X ziziphus/pkg/version.GitCommit=$(GIT_HASH)" -o /tmp/ziziphus-linux ./cmd/ziziphus/
	@echo "=== 3/3 Push to remote server ==="
	ssh -p $(SSH_PORT) $(DEPLOY_USER)@$(SSH_HOST) "systemctl stop ziziphus 2>/dev/null || true; sleep 1"
	ssh -p $(SSH_PORT) $(DEPLOY_USER)@$(SSH_HOST) "mkdir -p $(DEPLOY_PATH)/internal/storage/db/migrations"
	scp -P $(SSH_PORT) /tmp/ziziphus-linux $(DEPLOY_USER)@$(SSH_HOST):$(DEPLOY_PATH)/ziziphus
	ssh -p $(SSH_PORT) $(DEPLOY_USER)@$(SSH_HOST) "chmod +x $(DEPLOY_PATH)/ziziphus"
	sed 's/^  port:.*/  port: $(DEPLOY_PORT)/; s|^  dsn:.*|  dsn: "$(DEPLOY_DSN)"|' server/config/config.yaml > /tmp/ziziphus-config.yaml
	scp -P $(SSH_PORT) /tmp/ziziphus-config.yaml $(DEPLOY_USER)@$(SSH_HOST):$(DEPLOY_PATH)/config.yaml
	scp -P $(SSH_PORT) server/internal/storage/db/migrations/*.sql $(DEPLOY_USER)@$(SSH_HOST):$(DEPLOY_PATH)/internal/storage/db/migrations/
	rm -f /tmp/ziziphus-linux /tmp/ziziphus-config.yaml
	printf '%s\n' '[Unit]' 'Description=Ziziphus Server' 'After=network.target' '' '[Service]' 'Type=simple' 'WorkingDirectory=$(DEPLOY_PATH)' 'ExecStart=$(DEPLOY_PATH)/ziziphus -c $(DEPLOY_PATH)/config.yaml' 'Restart=always' 'RestartSec=5' '' '[Install]' 'WantedBy=multi-user.target' > /tmp/ziziphus.service
	scp -P $(SSH_PORT) /tmp/ziziphus.service $(DEPLOY_USER)@$(SSH_HOST):/etc/systemd/system/ziziphus.service
	rm -f /tmp/ziziphus.service
	ssh -p $(SSH_PORT) $(DEPLOY_USER)@$(SSH_HOST) "systemctl daemon-reload && systemctl start ziziphus"
	ssh -p $(SSH_PORT) $(DEPLOY_USER)@$(SSH_HOST) "systemctl status ziziphus --no-pager"

deploy-status:
	ssh -p $(SSH_PORT) $(DEPLOY_USER)@$(SSH_HOST) "systemctl status ziziphus --no-pager"

deploy-logs:
	ssh -p $(SSH_PORT) $(DEPLOY_USER)@$(SSH_HOST) "journalctl -u ziziphus -n 100 --no-pager -f"