ALTER TABLE users ADD COLUMN IF NOT EXISTS email VARCHAR(256) NOT NULL DEFAULT '';

CREATE TABLE IF NOT EXISTS user_mfa (
    user_id    VARCHAR(32) PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    mfa_type   SMALLINT NOT NULL DEFAULT 0,  -- 0=none, 1=totp, 2=email
    enabled    BOOLEAN NOT NULL DEFAULT FALSE,
    secret     VARCHAR(256) NOT NULL DEFAULT '',
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);
